speakers:
  indrek:
    languages: [est]
  kylli:
    languages: [est]
  lee:
    languages: [est]
  liisi:
    languages: [est]
  liivika:
    languages: [est]
  peeter:
    languages: [est]
  riina:
    languages: [est]
  tambet_otsekone:
    languages: [est]
  tambet_yksiklaused:
    languages: [est]
  tonu:
    languages: [est]
alt_names:
  külli: kylli