vocoders:
  vctk: models/hifigan/vctk # the directory which should contain a .json and .pt file
  ljspeech: models/hifigan/ljspeech
tts_models:
  merlin:
    model_path: /app/mrln_et_light # Absolute path to merlin directory
    frontend: 'est'
    speakers:
      merlin_indrek:
        speaker_id: 0
        vocoder: ''
      merlin_kylli:
        speaker_id: 1
        vocoder: ''
      merlin_lee:
        speaker_id: 2
        vocoder: ''
      merlin_liisi:
        speaker_id: 3
        vocoder: ''
      merlin_liivika:
        speaker_id: 4
        vocoder: ''
      merlin_peeter:
        speaker_id: 5
        vocoder: ''
      merlin_riina:
        speaker_id: 6
        vocoder: ''
      merlin_tambet_otsekone:
        speaker_id: 7
        vocoder: ''
      merlin_tambet_yksiklaused:
        speaker_id: 8
        vocoder: ''
      merlin_tonu:
        speaker_id: 9
        vocoder: ''
  
  # single-speaker example:
  #  mari:
  #    model_path: models/tts/mari
  #    frontend: 'est'
  #    speakers:
  #      lee:
  #        speaker_id: 0
  #        vocoder: ljspeech