vocoders:
  vctk: models/hifigan/vctk # the directory which should contain a .json and .pt file
  ljspeech: models/hifigan/ljspeech
tts_models:
  merlin:
    model_path: /app/mrln_et_light # Absolute path to merlin directory
    frontend: 'est'
    speakers:
      indrek:
        speaker_id: 0
        vocoder: ''
      kylli:
        speaker_id: 1
        vocoder: ''
      lee:
        speaker_id: 2
        vocoder: ''
      liisi:
        speaker_id: 3
        vocoder: ''
      liivika:
        speaker_id: 4
        vocoder: ''
      peeter:
        speaker_id: 5
        vocoder: ''
      riina:
        speaker_id: 6
        vocoder: ''
      tambet_otsekone:
        speaker_id: 7
        vocoder: ''
      tambet_yksiklaused:
        speaker_id: 8
        vocoder: ''
      tonu:
        speaker_id: 9
        vocoder: ''
  
  # single-speaker example:
  #  mari:
  #    model_path: models/tts/mari
  #    frontend: 'est'
  #    speakers:
  #      lee:
  #        speaker_id: 0
  #        vocoder: ljspeech